[package]
name = "cairo-language-common"
version = "0.1.0"
edition = "2024"

[dependencies]
cairo-lang-defs = "*"
cairo-lang-diagnostics = "*"
cairo-lang-filesystem = "*"
cairo-lang-parser = "*"
cairo-lang-semantic = "*"
cairo-lang-syntax = "*"
cairo-lang-utils = "*"
salsa = "0.24.0"
tracing = "0.1"

# Here we specify real dependency specifications for Cairo crates *if* currently we want to use
# a particular unreleased commit (which is frequent mid-development).
# We list all Cairo crates that go into Scarb's compilation unit even if Scarb itself does not depend
# on some of them directly.
# This ensures no duplicate instances of Cairo crates are pulled in by mistake.
[patch.crates-io]
cairo-lang-defs = { git = "https://github.com/starkware-libs/cairo", rev = "0f73d7cb5a0db79d8ad215442e6a7794f76e7c20" }
cairo-lang-diagnostics = { git = "https://github.com/starkware-libs/cairo", rev = "0f73d7cb5a0db79d8ad215442e6a7794f76e7c20" }
cairo-lang-filesystem = { git = "https://github.com/starkware-libs/cairo", rev = "0f73d7cb5a0db79d8ad215442e6a7794f76e7c20" }
cairo-lang-parser = { git = "https://github.com/starkware-libs/cairo", rev = "0f73d7cb5a0db79d8ad215442e6a7794f76e7c20" }
cairo-lang-semantic = { git = "https://github.com/starkware-libs/cairo", rev = "0f73d7cb5a0db79d8ad215442e6a7794f76e7c20" }
cairo-lang-syntax = { git = "https://github.com/starkware-libs/cairo", rev = "0f73d7cb5a0db79d8ad215442e6a7794f76e7c20" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo", rev = "0f73d7cb5a0db79d8ad215442e6a7794f76e7c20" }
