[package]
name = "cairo-language-common"
description = "Common Cairo compiler utils."
version = "2.15.0"
edition = "2024"
repository = "https://github.com/software-mansion/cairo-language-common"
license = "Apache-2.0"

[dependencies]
cairo-lang-defs = "*"
cairo-lang-diagnostics = "*"
cairo-lang-filesystem = "*"
cairo-lang-parser = "*"
cairo-lang-semantic = "*"
cairo-lang-syntax = "*"
cairo-lang-utils = "*"
salsa = "0.26.0"
semver = "1"
tracing = "0.1"

# Here we specify real dependency specifications for Cairo crates *if* currently we want to use
# a particular unreleased commit (which is frequent mid-development).
# We list all Cairo crates that go into Scarb's compilation unit even if Scarb itself does not depend
# on some of them directly.
# This ensures no duplicate instances of Cairo crates are pulled in by mistake.
[patch.crates-io]
cairo-lang-defs = { git = "https://github.com/starkware-libs/cairo/", rev = "bf4bb15a41094a08b06c7b1c502ffaa47d49aa8a" }
cairo-lang-diagnostics = { git = "https://github.com/starkware-libs/cairo/", rev = "bf4bb15a41094a08b06c7b1c502ffaa47d49aa8a" }
cairo-lang-filesystem = { git = "https://github.com/starkware-libs/cairo/", rev = "bf4bb15a41094a08b06c7b1c502ffaa47d49aa8a" }
cairo-lang-parser = { git = "https://github.com/starkware-libs/cairo/", rev = "bf4bb15a41094a08b06c7b1c502ffaa47d49aa8a" }
cairo-lang-semantic = { git = "https://github.com/starkware-libs/cairo/", rev = "bf4bb15a41094a08b06c7b1c502ffaa47d49aa8a" }
cairo-lang-syntax = { git = "https://github.com/starkware-libs/cairo/", rev = "bf4bb15a41094a08b06c7b1c502ffaa47d49aa8a" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo/", rev = "bf4bb15a41094a08b06c7b1c502ffaa47d49aa8a" }
