[package]
name = "cairo-language-common"
description = "Common Cairo compiler utils."
version = "2.15.0-rc.1"
edition = "2024"
license = "Apache-2.0"

[dependencies]
cairo-lang-defs = "2.15.0-rc.1"
cairo-lang-diagnostics = "2.15.0-rc.1"
cairo-lang-filesystem = "2.15.0-rc.1"
cairo-lang-parser = "2.15.0-rc.1"
cairo-lang-semantic = "2.15.0-rc.1"
cairo-lang-syntax = "2.15.0-rc.1"
cairo-lang-utils = "2.15.0-rc.1"
salsa = "0.24.0"
semver = "1"
tracing = "0.1"

# Here we specify real dependency specifications for Cairo crates *if* currently we want to use
# a particular unreleased commit (which is frequent mid-development).
# We list all Cairo crates that go into Scarb's compilation unit even if Scarb itself does not depend
# on some of them directly.
# This ensures no duplicate instances of Cairo crates are pulled in by mistake.
[patch.crates-io]
